[package]
name = "rust-chip8"
version = "0.1.0"
authors = ["James Middleton <hello@jamesmiddleton.me>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cpal = "0.12.1"
minifb = "0.19.1"
rand = "0.7.3"
